server:
  port: 8761

spring:
  application:
    name: SERVICE-REGISTRY

eureka:
  client:
    register-with-eureka: false   # server does not register itself
    fetch-registry: false         # server does not fetch registry
  
